version: '2'
services:
  rest-proxy:
    image: confluentinc/cp-kafka-rest:7.2.1
    ports:
      - 8082:8082
    networks:
      - confluent
    hostname: rest-proxy
    container_name: rest-proxy
    environment:
      KAFKA_REST_HOST_NAME: rest-proxy
      KAFKA_REST_BOOTSTRAP_SERVERS: 'kafka-1:9092'
      KAFKA_REST_LISTENERS: "http://0.0.0.0:8082"
      KAFKA_REST_SCHEMA_REGISTRY_URL: 'http://schema-registry:8081'

networks:
  confluent:
    external: true