spring:
  kafka:
    bootstrap-servers: localhost:19092,localhost:29092,localhost:39092
    schema-registry-url: http://localhost:8081
    topics:
      avro-order: testing-avro-order
      person: testing-person
      order-enriched: testing-order-enriched
      customer-summary: testing-customer-summary